Content = {
    months: 
		{ 	 '01': "Janeiro",
			 '02': "Fevereiro",
			 '03': "Mar&#231;o",
			 '04': "Abril",
			 '05': "Maio",
			 '06': "Junho",
			 '07': "Julho",
			 '08': "Agosto",
			 '09': "Setembro",
			 '10': "Outubro",
			 '11': "Novembro",
			 '12': "Dezembro",
		},
    shortMonths: 
		{ 	 '01': "Jan",
			 '02': "Fev",
			 '03': "Mar",
			 '04': "Abr",
			 '05': "Mai",
			 '06': "Jun",
			 '07': "Jul",
			 '08': "Ago",
			 '09': "Set",
			 '10': "Out",
			 '11': "Nov",
			 '12': "Dez",
		},
    savedInArchive:"Foram gravadas no arquivo",
    versionsStored:"Tabela de vers&#245;es",
    versionsPage:"vers&#245;es de",
    between:"entre",
    and:"e",
    resultsQuestion:"Pretendia ver os resultados das p&#225;ginas que cont&#234;m o texto:",
    moreOptions:"Mais op&#231;&#245;es",
    lessOptions:"Menos op&#231;&#245;es",
    help:"Ajuda",
    helpHref:"http://sobre.arquivo.pt/ajuda",
    newSearch:"Nova pesquisa",
    at:"&#224;s",
    shareMessage:"Arquivo.pt",
    language:"pt",
    otherDates:"Tabela de vers&#245;es",
    emailMessage:"Pagina Interessante Do Passado &body=",
    noResultsFound:"N&#227;o foram encontrados resultados para a sua pesquisa:",
    suggestions:"Sugerimos que:",
    checkSpelling:"Verifique o URL",
    differentKeywords:"Tente utilizar outras palavras-chave.",
    generalWords:"Tente palavras mais gerais.", 
    internetArchive:"Pesquise no",
    suggestSiteArchived:"a p&#225gina para que seja arquivada.",
    suggestUrl:"http://sobre.arquivo.pt/colaboracoes/sugerir-um-sitio?endereco-a-sugerir=",
    suggest:"Sugira", 
    mementoFind:"Pesquise outros arquivos web",
    embargo:"Embargo",
    embargoUrl:"http://sobre.arquivo.pt/ajuda/acesso-a-conteudos-arquivados#section-6",
    notArchived:"N&#227;o Arquivado",
    otherLanguage: "EN"  ,
    preservedByArquivo: " - preservado pelo Arquivo.pt"     
};
