Content = {
    months: 
		{ 	 '01': "January",
			 '02': "February",
			 '03': "March",
			 '04': "April",
			 '05': "May",
			 '06': "June",
			 '07': "July",
			 '08': "August",
			 '09': "September",
			 '10': "October",
			 '11': "November",
			 '12': "December",
		},
    shortMonths: 
		{ 	 '01': "Jan",
			 '02': "Feb",
			 '03': "Mar",
			 '04': "Apr",
			 '05': "May",
			 '06': "Jun",
			 '07': "Jul",
			 '08': "Aug",
			 '09': "Sep",
			 '10': "Oct",
			 '11': "Nov",
			 '12': "Dez",
		},
    savedInArchive:"We archived",
    versionsStored:"Versions table",
    versionsPage:"versions of",
    between:"between",
    and:"and",
    resultsQuestion:"Did you want to see webpages with the text:",
    moreOptions:"More options",
    lessOptions:"Less options",
    help:"Help",
    helpHref:"http://sobre.arquivo.pt/help/faq?set_language=en",
    newSearch:"New search",
    at:"at",
    shareMessage:"Arquivo.pt: search pages from the past.",
    language:"en",
    otherDates:"Versions table",
    emailMessage:"Interesting Web Page from the Past &body=",
    noResultsFound:"No results were found for the query:",
    suggestions:"We suggest that you:",
    checkSpelling:"Verify the URL.",
    differentKeywords:"Try different keywords.",
    generalWords:"Try more general words.",
    internetArchive:"Search the",
    suggestSiteArchived:"the site to be archived.", 
    suggestUrl:"http://sobre.arquivo.pt/how-to-participate/suggest-a-site?suggested-site=",
    suggest:"Suggest", 
    mementoFind:"Search other web archives",
    embargo:"Embargo",
    embargoUrl:"http://sobre.arquivo.pt/help/access-to-archived-contents#section-6",
    notArchived:"Not Archived",
    otherLanguage: "PT" ,
    preservedByArquivo: " - preserved by Arquivo.pt"  
};
