/* Generated By:JavaCC: Do not edit this line. TRECParserConstants.java */
package org.archive.nutch.trec;

public interface TRECParserConstants {

  int EOF = 0;
  int DOC_BEGIN = 1;
  int DOCNO_BEGIN = 2;
  int DOCNO_END = 3;
  int OLDDOCNO_BEGIN = 4;
  int OLDDOCNO_END = 5;
  int DOCNO = 6;
  int DOCHDR_BEGIN = 7;
  int URL_BGN = 8;
  int HEADER_LABEL = 9;
  int HEADER_CONTENT = 10;
  int HEADER_END = 11;
  int DOCHDR_END = 12;
  int CODE = 13;
  int MSGU = 14;
  int HEND = 15;
  int URLTXT = 16;
  int UMSGBGN = 17;
  int URLEND = 18;
  int UMSGBODY = 19;
  int UMSGEND = 20;
  int DOC_END = 21;
  int BODY = 22;

  int DEFAULT = 0;
  int DOCHDR = 1;
  int DOCTXT = 2;
  int HTTPBDY = 3;
  int URLBDY = 4;
  int URLMSG = 5;
  int DOCBODY = 6;

  String[] tokenImage = {
    "<EOF>",
    "\"<DOC>\"",
    "\"<DOCNO>\"",
    "\"</DOCNO>\"",
    "\"<DOCOLDNO>\"",
    "\"</DOCOLDNO>\"",
    "<DOCNO>",
    "\"<DOCHDR>\\n\"",
    "\"http://\"",
    "<HEADER_LABEL>",
    "<HEADER_CONTENT>",
    "<HEADER_END>",
    "\"</DOCHDR>\"",
    "<CODE>",
    "<MSGU>",
    "<HEND>",
    "<URLTXT>",
    "\" \"",
    "<URLEND>",
    "<UMSGBODY>",
    "<UMSGEND>",
    "\"</DOC>\"",
    "<BODY>",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "\" \"",
  };

}
